### ISSUE TITLE
Delineating releases - What the heck are we doing

### ISSUE THREAD

**Issue by 11acc** [solsylph/Debate-Chatbot#6]
These should be the main releases we should have at the very least for the project itself. Let's aim to have release v0.1 done and v0.2 started before spring break.

Release v0.1
- Make Lorenzo's frontend skeleton online so that anyone can access it

Release v0.2
- Connect the website to Azure and database
- Connect simplest model and dataset so that something responds when "chatting" (even if its gibberish)

Release v0.3
- Upgrade models and datasets present on the webapp so that the chatbot is slowly becoming the chatbot

This is a general issue in order to not only get started with using the repo more, but organising our direction.

Let's make something cool guys :)

**Comment by solsylph** [comment]
i would assume that for v0.1 the site would have to be deployed using an azure resource right? we won't just be running and testing in our local env. also, i'm pretty sure that since we're using this for javascript II that we also need to use react components so this counts as credit for the class final project
